name: my_system_android
description: Android implementation of the my_system plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: my_system
    platforms:
      android:
        package: com.example.verygoodcore
        pluginClass: MySystemPlugin
        dartPluginClass: MySystemAndroid

dependencies:
  flutter:
    sdk: flutter
  my_system_platform_interface:
    path: ../my_system_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
